// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGtay219MxtaR7Xo2uTrCj_nUEnDnR9_o',
    appId: '1:501602137585:web:e4b471041a06e5b1004050',
    messagingSenderId: '501602137585',
    projectId: 'fir-crew-f7c5c',
    authDomain: 'fir-crew-f7c5c.firebaseapp.com',
    storageBucket: 'fir-crew-f7c5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApLnGkeXkErMsw7LMphu2n8mt-qQR2oJA',
    appId: '1:501602137585:android:d5fb1e9460c0fed4004050',
    messagingSenderId: '501602137585',
    projectId: 'fir-crew-f7c5c',
    storageBucket: 'fir-crew-f7c5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZBiC1bws4fPMld4QuNXLxnlzLHJrhtrE',
    appId: '1:501602137585:ios:7de7370b42c2e76f004050',
    messagingSenderId: '501602137585',
    projectId: 'fir-crew-f7c5c',
    storageBucket: 'fir-crew-f7c5c.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZBiC1bws4fPMld4QuNXLxnlzLHJrhtrE',
    appId: '1:501602137585:ios:a86eddce4d353af7004050',
    messagingSenderId: '501602137585',
    projectId: 'fir-crew-f7c5c',
    storageBucket: 'fir-crew-f7c5c.appspot.com',
    iosBundleId: 'com.example.brewCrew.RunnerTests',
  );
}
